export const FETCH_MERCHANT_BOOKS_SUCCESS = 'FETCH_MERCHANT_BOOKS_SUCCESS';
export const FETCH_MERCHANT_BOOKS_FAIL = 'FETCH_MERCHANT_BOOKS_FAIL';
export const FETCH_GENRES_SUCCESS = 'FETCH_GENRES_SUCCESS';
export const FETCH_GENRES_FAIL = 'FETCH_GENRES_FAIL';