export const FETCH_FORM_SUCCESS = 'FETCH_FORM_SUCCESS';
export const FETCH_FORM_FAIL = 'FETCH_FORM_FAIL';
export const VALIDATE_SUCCESS = 'VALIDATE_SUCCESS';
export const VALIDATE_FAIL = 'VALIDATE_FAIL';
export const CLEAR_VALIDATION = 'CLEAR_VALIDATION';
export const SET_ARRAY = 'SET_ARRAY';