server:
  port: 8100
  ssl:
    enabled: true
    key-alias: ${KEYSTORE_ALIAS:bank}
    key-store: ${KEYSTORE:classpath:bank.keystore.p12}
    key-store-password: ${KEYSTORE_PASSWORD:password}
    key-store-type: ${KEYSTORE_TYPE:PKCS12}
    trust-store: ${TRUSTSTORE:classpath:bank.truststore.p12}
    trust-store-password: ${TRUSTSTORE_PASSWORD:password}
    trust-store-type: ${TRUSTSTORE_TYPE:PKCS12}
    client-auth: want

spring:
  application:
    name: ${SPRINGBOOT_APP_NAME:bank}
  datasource:
    username: ${DATABASE_USERNAME:nitpicksy_user}
    password: ${DATABASE_PASSWORD:Nitpicksy-2020}
    url: jdbc:mysql://${DATABASE_DOMAIN:localhost}:${DATABASE_PORT:3306}/${DATABASE_SCHEMA:bank}?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    platform: mysql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  mail:
    host: smtp.gmail.com
    username: konstrukcijaitestsoftvera2020@gmail.com
    password: KTS2020Projekat
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
eureka:
  client:
    service-url:
      defaultZone: https://eureka-peer1:8761/eureka, https://eureka-peer2:8762/eureka
      healthcheck:
        enabled: true
    fetchRegistry: true
  instance:
    hostname: localhost
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
    homePageUrl: https://${eureka.instance.hostname}:${server.port}/
    secureVirtualHostName: ${spring.application.name}
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}

BANK_IDENTIFICATION_NUMBER: 123456

