export const FETCH_MEMBERSHIP_SUCCESS = 'FETCH_MEMBERSHIP_SUCCESS';
export const FETCH_MEMBERSHIP_FAIL = 'FETCH_MEMBERSHIP_FAIL';
export const FETCH_PRICE_LIST_SUCCESS = 'FETCH_PRICE_LIST_SUCCESS';
export const FETCH_PRICE_LIST_FAIL = 'FETCH_PRICE_LIST_FAIL';