export const SIGN_UP_TYPE = 'SIGN_UP_TYPE';
export const START_PROCESS_SUCCESS = 'START_PROCESS_SUCCESS';
export const START_PROCESS_FAIL = 'START_PROCESS_FAIL';
export const CLEAR_PROCESS_STATE = 'CLEAR_PROCESS_STATE';