server:
  port: 8076

spring:
  application:
    name: ${SPRINGBOOT_APP_NAME:bitcoin-service}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-peer1:8761/eureka,http://eureka-peer2:8760/eureka
      healthcheck:
        enabled: true
    fetchRegistry: true