server:
  port: 8300
  ssl:
    enabled: true
    key-alias: ${KEYSTORE_ALIAS:bitcoin}
    key-store: ${KEYSTORE:classpath:bitcoin.keystore.p12}
    key-store-password: ${KEYSTORE_PASSWORD:password}
    key-store-type: ${KEYSTORE_TYPE:PKCS12}
    trust-store: ${TRUSTSTORE:classpath:bitcoin.truststore.p12}
    trust-store-password: ${TRUSTSTORE_PASSWORD:password}
    trust-store-type: ${TRUSTSTORE_TYPE:PKCS12}
    client-auth: want

spring:
  application:
    name: ${SPRINGBOOT_APP_NAME:bitcoin}
  datasource:
    username: ${DATABASE_USERNAME:nitpicksy_user}
    password: ${DATABASE_PASSWORD:Nitpicksy-2020}
    url: jdbc:mysql://${DATABASE_DOMAIN:localhost}:${DATABASE_PORT:3306}/${DATABASE_SCHEMA:bitcoin_service}?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false

eureka:
  client:
    service-url:
      defaultZone: https://eureka-peer1:8761/eureka, https://eureka-peer2:8762/eureka
      healthcheck:
        enabled: true
    fetchRegistry: true
  instance:
    hostname: localhost
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
    homePageUrl: https://${eureka.instance.hostname}:${server.port}/
    secureVirtualHostName: ${spring.application.name}
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}

API_KEY: js4zu_8ezKs1wy_wswvrkm8JHm5L-9JBujvKznLE
SANDBOX_ENVIRONMENT: https://api-sandbox.coingate.com/v2
TOKEN_UTILS_SECRET: Nitpicsky

CALLBACK_URL: https://b93fc3de3f52.ngrok.io/api/payments/callback