server:
  port: 8888
  ssl:
    enabled: true
    key-alias: ${KEYSTORE_ALIAS:cloud}
    key-store: ${KEYSTORE:classpath:cloud.keystore.p12}
    key-store-password: ${KEYSTORE_PASSWORD:password}
    key-store-type: ${KEYSTORE_TYPE:PKCS12}
    trust-store: ${TRUSTSTORE:classpath:cloud.truststore.p12}
    trust-store-password: ${TRUSTSTORE_PASSWORD:password}
    trust-store-type: ${TRUSTSTORE_TYPE:PKCS12}
    client-auth: want

eureka:
  client:
    service-url:
      defaultZone: https://eureka-peer1:8761/eureka, https://eureka-peer2:8762/eureka
      healthcheck:
        enabled: true
    fetchRegistry: true
  instance:
    hostname: localhost
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
    homePageUrl: https://${eureka.instance.hostname}:${server.port}/
    secureVirtualHostName: ${spring.application.name}
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}

management:
  endpoints:
    web:
      exposure:
        include: '*'