server:
  port: 8080
  ssl:
    enabled: false
    key-alias: ${KEYSTORE_ALIAS:zuul}
    key-store: ${KEYSTORE:classpath:zuul.keystore.p12}
    key-store-password: ${KEYSTORE_PASSWORD:password}
    key-store-type: ${KEYSTORE_TYPE:PKCS12}
    trust-store: ${TRUSTSTORE:classpath:zuul.truststore.p12}
    trust-store-password: ${TRUSTSTORE_PASSWORD:password}
    trust-store-type: ${TRUSTSTORE_TYPE:PKCS12}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      healthcheck-enabled: true
#  instance:
#    nonSecurePortEnabled: false
#    securePortEnabled: true
#    securePort: ${server.port}
#    homePageUrl: https://${eureka.instance.hostname}:${server.port}/
#    secureVirtualHostName: ${spring.application.name}
#    prefer-ip-address: false

zuul:
  routes:
    payment-gateway:
      path: /payment-gateway/**
      service-id: payment-gateway
    literary-society:
      path: /literary-society/**
      url: https://localhost:8090
    #      service-id: literary-society
    bank:
      path: /bank/**
      url: http://localhost:8100
    bank2:
      path: /bank2/**
      url: http://localhost:8102
    pcc:
      path: /pcc/**
      url: http://localhost:8101
    paypal-service:
      path: /paypal-service/**
      url: http://localhost:8200
    bitcoin-service:
      path: /bitcoin-service/**
      url: http://localhost:8300
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  #  prefix: /api
  ignored-services: '*'
  sslHostnameValidationEnabled: false

ribbon:
  eureka:
    enabled: true
  IsSecure: true
  ReadTimeout: 60000
  ConnectTimeout: 6000
  TrustStore: ${TRUSTSTORE:classpath:zuul.truststore.p12}
  TrustStorePassword: ${TRUSTSTORE_PASSWORD:password}
  CustomSSLSocketFactoryClassName: com.netflix.http4.ssl.AcceptAllSocketFactory
  IsHostnameValidationRequired: false

#literary-society:
#  ribbon:
#    listOfServers: https://localhost:8090

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 132000

test:
  value: zdravo

bitcoin:
  uri: https://bitcoin.com

management:
  endpoints:
    web:
      exposure:
        include: '*'