server:
  port: 8080
  ssl:
    enabled: true
    key-alias: ${KEYSTORE_ALIAS:zuul}
    key-store: ${KEYSTORE:classpath:zuul.keystore.p12}
    key-store-password: ${KEYSTORE_PASSWORD:password}
    key-store-type: ${KEYSTORE_TYPE:PKCS12}
    trust-store: ${TRUSTSTORE:classpath:zuul.truststore.p12}
    trust-store-password: ${TRUSTSTORE_PASSWORD:password}
    trust-store-type: ${TRUSTSTORE_TYPE:PKCS12}
    client-auth: want

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://localhost:8761/eureka
      healthcheck-enabled: true
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
    homePageUrl: https://${eureka.instance.hostname}:${server.port}/
    secureVirtualHostName: ${spring.application.name}
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    hostname: localhost

zuul:
  routes:
    payment-gateway:
      path: /payment-gateway/**
      service-id: payment-gateway
    literary-society:
      path: /literary-society/**
      #      url: http://localhost:8090
      service-id: literary-society
    bank:
      path: /bank/**
      #      url: http://localhost:8100
      service-id: bank
    pcc:
      path: /pcc/**
      #      url: http://localhost:8101
      service-id: pcc
    paypal:
      path: /paypal/**
      #      url: http://localhost:8200
      service-id: paypal
    bitcoin:
      path: /bitcoin/**
      #      url: http://localhost:8300
      service-id: bitcoin
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  #  prefix: /api
  ignored-services: '*'
  sslHostnameValidationEnabled: false

ribbon:
  eureka:
    enabled: true
  IsSecure: true
  ReadTimeout: 60000
  ConnectTimeout: 6000
  TrustStore: ${TRUSTSTORE:classpath:zuul.truststore.p12}
  TrustStorePassword: ${TRUSTSTORE_PASSWORD:password}
  CustomSSLSocketFactoryClassName: com.netflix.http4.ssl.AcceptAllSocketFactory
  IsHostnameValidationRequired: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 132000

test:
  value: zdravo

bitcoin:
  uri: https://bitcoin.com

management:
  endpoints:
    web:
      exposure:
        include: '*'