export const FETCH_PAYMENT_METHODS_START = "FETCH_PAYMENT_METHODS_START";
export const FETCH_PAYMENT_METHODS_END = "FETCH_PAYMENT_METHODS_END";

export const FETCH_PAYMENT_DETAILS_START = "FETCH_PAYMENT_DETAILS_START";
export const FETCH_PAYMENT_DETAILS_END = "FETCH_PAYMENT_DETAILS_END";
