peers:
  port1: 8761
  port2: 8762

---
server:
  port: ${peers.port1}
spring:
  config:
    activate:
      on-profile: peer1
eureka:
  instance:
    hostname: eureka-peer1
    appname: eureka-cluster
  client:
    serviceUrl:
      defaultZone: http://eureka-peer2:${peers.port2}/eureka
    register-with-eureka: false
    fetch-registry: false

---
server:
  port: ${peers.port2}
spring:
  config:
    activate:
      on-profile: peer2
eureka:
  instance:
    hostname: eureka-peer2
    appname: eureka-cluster
  client:
    serviceUrl:
      defaultZone: http://eureka-peer1:${peers.port1}/eureka
    register-with-eureka: false
    fetch-registry: false
