peers:
  port1: 8761
  port2: 8762

server:
  ssl:
    enabled: true
    key-alias: ${KEYSTORE_ALIAS:eureka}
    key-store: ${KEYSTORE:classpath:eureka.keystore.p12}
    key-store-password: ${KEYSTORE_PASSWORD:password}
    key-store-type: ${KEYSTORE_TYPE:PKCS12}
    trust-store: ${TRUSTSTORE:classpath:eureka.truststore.p12}
    trust-store-password: ${TRUSTSTORE_PASSWORD:password}
    trust-store-type: ${TRUSTSTORE_TYPE:PKCS12}
---
server:
  port: ${peers.port1}
spring:
  config:
    activate:
      on-profile: peer1
eureka:
  instance:
    hostname: eureka-peer1
    appname: eureka-cluster
    nonSecurePortEnabled: false
    securePortEnabled: true
    secure-port: ${server.port}
    prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: https://eureka-peer1:${peers.port1}/eureka
    register-with-eureka: false
    fetch-registry: false
---
server:
  port: ${peers.port2}
spring:
  config:
    activate:
      on-profile: peer2
eureka:
  instance:
    hostname: eureka-peer2
    appname: eureka-cluster
    nonSecurePortEnabled: false
    securePortEnabled: true
    secure-port: ${server.port}
    prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: http://eureka-peer1:${peers.port1}/eureka
    register-with-eureka: false
    fetch-registry: false
