server:
  port: 8090
  ssl:
    enabled: false
    key-alias: ${KEYSTORE_ALIAS:literary}
    key-store: ${KEYSTORE:classpath:literary.keystore.p12}
    key-store-password: ${KEYSTORE_PASSWORD:password}
    key-store-type: ${KEYSTORE_TYPE:PKCS12}
    trust-store: ${TRUSTSTORE:classpath:literary.truststore.p12}
    trust-store-password: ${TRUSTSTORE_PASSWORD:password}
    trust-store-type: ${TRUSTSTORE_TYPE:PKCS12}
    client-auth: need

spring:
  application:
    name: ${SPRINGBOOT_APP_NAME:literary-society}
  datasource:
    username: ${DATABASE_USERNAME:nitpicksy_user}
    password: ${DATABASE_PASSWORD:Nitpicksy-2020}
    url: jdbc:mysql://${DATABASE_DOMAIN:localhost}:${DATABASE_PORT:3306}/${DATABASE_SCHEMA:literary_society}?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  mail:
    host: smtp.gmail.com
    username: teamvjn@gmail.com
    password: team29VJN
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
eureka:
  client:
    service-url:
      defaultZone: https://localhost:8761/eureka
      #,http://eureka-peer2:8762/eureka
      healthcheck:
        enabled: true
    fetchRegistry: true
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
    homePageUrl: https://${eureka.instance.hostname}:${server.port}/
    secureVirtualHostName: ${spring.application.name}

ribbon:
  IsSecure: true

TOKEN_UTILS_APP_NAME: literary-society
TOKEN_UTILS_SECRET: Nitpicsky
# 15 min
#TOKEN_UTILS_EXPIRES_IN: 10800000
TOKEN_UTILS_EXPIRES_IN: 10800000
# 14 days
TOKEN_UTILS_REFRESH_TOKEN_EXPIRES_IN: 1209600000
TOKEN_UTILS_AUTH_HEADER: Authorization
# Localhost
LOCALHOST_URL: http://localhost:3000/

