export const FETCH_PUBLICATION_REQUESTS_SUCCESS = 'FETCH_PUBLICATION_REQUESTS_SUCCESS';
export const FETCH_PUBLICATION_REQUESTS_FAIL = 'FETCH_PUBLICATION_REQUESTS_FAIL';
export const START_PROCESS_SUCCESS = 'START_PROCESS_SUCCESS';
export const START_PROCESS_FAIL = 'START_PROCESS_FAIL';
export const CLEAR_PROCESS_STATE = 'CLEAR_PROCESS_STATE';