#server:
#  port: 8103
server:
  port: ${PORT:0}

spring:
  application:
    name: ${SPRINGBOOT_APP_NAME:payment-gateway}

eureka:
  client:
    service-url:
      defaultZone: http://${REGISTRY_HOST:localhost}:${REGISTRY_PORT:8761}/eureka/
      healthcheck:
        enabled: true
    fetchRegistry: true
  instance:
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
