#server:
#  port: 8103
server:
  port: ${PORT:0}

spring:
  application:
    name: ${SPRINGBOOT_APP_NAME:payment-gateway}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-peer1:8761/eureka,http://eureka-peer2:8760/eureka
      healthcheck:
        enabled: true
    fetchRegistry: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
