server:
  port: ${PORT:0}
  ssl:
    enabled: false
    key-alias: ${KEYSTORE_ALIAS:gateway}
    key-store: ${KEYSTORE:classpath:gateway.keystore.p12}
    key-store-password: ${KEYSTORE_PASSWORD:password}
    key-store-type: ${KEYSTORE_TYPE:PKCS12}
    trust-store: ${TRUSTSTORE:classpath:gateway.truststore.p12}
    trust-store-password: ${TRUSTSTORE_PASSWORD:password}
    trust-store-type: ${TRUSTSTORE_TYPE:PKCS12}

spring:
  application:
    name: ${SPRINGBOOT_APP_NAME:payment-gateway}
  datasource:
    username: ${DATABASE_USERNAME:nitpicksy_user}
    password: ${DATABASE_PASSWORD:Nitpicksy-2020}
    url: jdbc:mysql://${DATABASE_DOMAIN:localhost}:${DATABASE_PORT:3306}/${DATABASE_SCHEMA:payment_gateway}?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      #,http://eureka-peer2:8762/eureka
      healthcheck:
        enabled: true
    fetchRegistry: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#    secureVirtualHostName: ${spring.application.name}

ribbon:
  IsSecure: true
#
#paypal-service:
#  ribbon:
#    listOfServers: https://localhost:8200