export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS';
export const FETCH_DRAFTS_SUCCESS = 'FETCH_DRAFTS_SUCCESS';
export const FETCH_DRAFTS_FAIL = 'FETCH_DRAFTS_FAIL';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_FAIL = 'FETCH_COMMENTS_FAIL';
export const FETCH_FORM_SUCCESS = 'FETCH_FORM_SUCCESS';
