server:
  port: 8888

spring:
  application:
    name: ${SPRINGBOOT_APP_NAME:cloud-config}
  cloud:
    config:
      server:
        git:
          uri: https://github.com/n-dusan/cloud-config.git
          clone-on-start: true
          search-paths: /{application}
    bus:
      enabled: true
  rabbitmq:
    host: ${RMQ_HOST:localhost}
    port: ${RMQ_PORT:5672}
    username: ${RMQ_USERNAME:guest}
    password: ${RMQ_PASSWORD:guest}

eureka:
  client:
    service-url:
      defaultZone: http://${REGISTRY_HOST:localhost}:${REGISTRY_PORT:8761}/eureka/
      healthcheck:
        enabled: true
    fetchRegistry: true
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

management:
  endpoints:
    web:
      exposure:
        include: '*'